spring:
  profiles:
    active: prod
management:
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    name: Simple Todo Application API
    description: This is my first spring boot application
    version: 1.0.0

---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/springexample?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: POip0790
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate

---

spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2