spring:
  profiles:
    active: dev

---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/springexample?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: POip0790

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

---

spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /baza
  security:
    user:
      name: root
      password: root